### PR TITLE
Stop monkey-patching String with #snakecase

### LINKED ISSUE #101: dont monkeypatch String#snakecase
While savon no longer monkeypatches, nori still does.

related issue: https://github.com/savonrb/savon/issues/984

### PR DESCRIPTION
**Pull request by mchu**
**What kind of change is this?**
Fixes #101 

Stops the monkey patching of `#snakecase` onto `String`. 

**Did you add tests for your changes?**
Updated existing `String#snakecase` tests to test `Nori::StringUtils.snakecase`.

**Summary of changes**
Moved `String#snakecase` into a module class method.

**Other information**
Related to https://github.com/savonrb/savon/issues/984

### CODE REVIEW

**Comment by choosen** [comment]
Savon gave it breaking change, not monkeyPatch

> BC BREAKING Fix: #988 Savon no longer monkeypatches String#snakecase

You changed the util so it's hard to be compatible with Nori when somebody used  pointed out in readme before  'StringKey'.snakecase

It's of course good to not pollute String class, but it should be minor bump I suppose instead of bugfix

**Comment by pcai** [comment]
Yes in hindsight it would’ve been a point release as with Savon - sorry about that

**Comment by testdocument99-cyber** [comment]
Can we use `underscore` method from `Activesupport` replacements `nori::StringUtils.snakecase ` 
@pcai @choosen

**Comment by pcai** [comment]
No, sorry, nori does not depend on activesupport so it cannot use activesupport methods

**Pull request merged**
